### ISSUE TITLE
Treat UnwillingToPerformError like an InvalidCredentialsError

### ISSUE THREAD

**Issue by melloc** [trentm/node-ldapauth#29]
When attempting to pass a zero-length password to a server that doesn't allow unauthenticated binds, the client returns an `UnwillingToPerformError`, which results in `ldapauth` trying to authenticate again. When this happens, the client is still connected to the server, so the backoff attempt ends up leaking clients, and getting stuck in a loop that will never end.

**Comment by trentm** [comment]
Note to self: See SYSOPS-164 for internal details.

Thanks Cody!
